tap thoughtbot/formulae
install rcm
install ant
install encfs
install fwknop
install git
install libpqxx
install libyaml
install postgresql
install rbenv-gem-rehash
install ruby-build
install the_silver_searcher
install tree
install vim
install ansible
install autoconf
install automake
install bison
install boost
install geoip
install gettext
install glib
install gmp
install gnupg
install gnutls
install gpgme
install htop-osx
install irssi
install jq
install libassuan
install libffi
install libgcrypt
install libgpg-error
install libtasn1
install libtool
install mysql
install ncdu
install nettle
install nginx
install pwgen
install rbenv
install readline
install terminal-notifier
install tig
install watch
install wget
install youtube-dl
